#############################################################################
# Makefile for building: libqextserialport
# Generated by qmake (1.07a) (Qt 3.3.1) on: Mon May 29 09:05:01 2006
# Project:  qextserialport.pro
# Template: lib
# Command: $(QMAKE) -o qextserialport.make qextserialport.pro
#############################################################################

####### Compiler, tools and options

CC		=	gcc
CXX		=	g++
LEX		= flex
YACC		= byacc
CFLAGS	=	-Wall -O2 -fno-exceptions -fno-rtti  -DUNICODE -DQT_THREAD_SUPPORT -DQT_NO_DEBUG
CXXFLAGS	=	-Wall -O2 -fno-exceptions -fno-rtti  -DUNICODE -DQT_THREAD_SUPPORT -DQT_NO_DEBUG
LEXFLAGS	=
YACCFLAGS	=-d
INCPATH	=	 -I"$(QTDIR)\include" -I"R:\MY_CODE\TuxShopPro\src\serial" -I"win_moc" -I"C:\Qt\331mingw\mkspecs\win32-g++"
LIB	=	ar -ru
MOC		=	$(QTDIR)\bin\moc.exe
UIC		=	$(QTDIR)\bin\uic.exe
QMAKE		=	qmake
IDC		=	$(QTDIR)\bin\idc.exe
IDL		=	midl
ZIP		=	zip -r -9
DEF_FILE      =	
COPY_FILE	=       copy
COPY_DIR	=       copy
DEL_FILE	=       del
DEL_DIR	=       rmdir
MOVE		=       move
CHK_DIR_EXISTS =	if not exist
MKDIR		=	mkdir

####### Output directory

OBJECTS_DIR = mingw_obj
MOC_DIR = win_moc

####### Files

HEADERS =	qextserialbase.h \
		qextserialport.h \
		win_qextserialport.h
SOURCES =	qextserialbase.cpp \
		qextserialport.cpp \
		win_qextserialport.cpp
OBJECTS =	mingw_obj\qextserialbase.o \
		mingw_obj\qextserialport.o \
		mingw_obj\win_qextserialport.o
FORMS =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	mingw\libqextserialport.a

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: $(OBJECTS_DIR) $(MOC_DIR) $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LIB) $(TARGET) $(OBJECTS) $(OBJMOC)

mocables: $(SRCMOC)

$(OBJECTS_DIR):
	@if not exist $(OBJECTS_DIR) $(MKDIR) $(OBJECTS_DIR)

$(MOC_DIR):
	@if not exist $(MOC_DIR) $(MKDIR) $(MOC_DIR)

qextserialport.make: qextserialport.pro  C:\Qt\331mingw\mkspecs\win32-g++\qmake.conf 
	$(QMAKE) -o qextserialport.make qextserialport.pro
qmake: 
	@$(QMAKE) -o qextserialport.make qextserialport.pro

dist:
	$(ZIP) .zip .pro $(SOURCES) $(HEADERS) $(DIST) $(FORMS)

clean:
	-$(DEL_FILE) mingw_obj\qextserialbase.o
	-$(DEL_FILE) mingw_obj\qextserialport.o
	-$(DEL_FILE) mingw_obj\win_qextserialport.o
	-$(DEL_FILE) $(TARGET)


####### Compile

mingw_obj\qextserialbase.o: qextserialbase.cpp qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mingw_obj\qextserialbase.o qextserialbase.cpp

mingw_obj\qextserialport.o: qextserialport.cpp qextserialport.h \
		posix_qextserialport.h \
		win_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mingw_obj\qextserialport.o qextserialport.cpp

mingw_obj\win_qextserialport.o: win_qextserialport.cpp win_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mingw_obj\win_qextserialport.o win_qextserialport.cpp

####### Install

install:  

uninstall:  

